=== new333333/test2/trunk/ssf/web/docroot/WEB-INF/classes/dtd/definition_builder_config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
     Definition Builder schema
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="definitions" type="definitionsType"/>
  <xsd:element name="definition" type="definitionType"/>

  <xsd:element name="comment" type="xsd:string"/>

  <xsd:complexType name="definitionsType">
    <xsd:sequence>
      <xsd:element name="definition" type="definitionType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="item" type="itemType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="properties" type="propertiesType"  minOccurs="0" maxOccurs="1"/>
   </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="definitionType">
    <xsd:sequence>
      <xsd:element name="item" type="itemType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="operations" type="operationsType" minOccurs="0" maxOccurs="1"/>
   </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string"/>
    <xsd:attribute name="caption" type="xsd:string"/>
    <xsd:attribute name="type" type="xsd:string"/>
    <xsd:attribute name="nextId" type="xsd:unsignedInt"/>
    <xsd:attribute name="canBeDeleted" type="xsd:string"/>
    <xsd:attribute name="definitionType" type="xsd:unsignedInt"/>
    <xsd:attribute name="replyStyle" type="xsd:string"/>
    <xsd:attribute name="databaseId" type="xsd:string"/>
    <xsd:attribute name="internalId" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="operationsType">
    <xsd:sequence>
      <xsd:element name="operation" type="operationType"  minOccurs="0" maxOccurs="unbounded"/>
   </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="operationType">
    <xsd:attribute name="name" type="xsd:string"/>
    <xsd:attribute name="caption" type="xsd:string"/>
    <xsd:attribute name="item" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="itemType">
    <xsd:sequence>
      <xsd:element name="properties" type="propertiesType"  minOccurs="0" maxOccurs="1"/>
      <xsd:element name="operations" type="operationsType"  minOccurs="0" maxOccurs="1"/>
      <xsd:element name="options" type="optionsType"  minOccurs="0" maxOccurs="1"/>
      <xsd:element name="option_entry_data" type="option_select_dataType" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="jsps" type="jspsType" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="folderViews" type="gwtFolderViewsType" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="item" type="itemType" minOccurs="0" maxOccurs="unbounded"/>
	  <xsd:element name="help" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="index" type="indexType"  minOccurs="0" maxOccurs="1"/>
      <xsd:element name="webService" type="webServiceType"  minOccurs="0" maxOccurs="1"/>
      <xsd:element name="export" type="exportType"  minOccurs="0" maxOccurs="1"/>
      <xsd:element name="notify" type="notifyType"  minOccurs="0" maxOccurs="1"/>
   </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string"/>
    <xsd:attribute name="caption" type="xsd:string"/>
    <xsd:attribute name="category" type="xsd:string"/>
    <xsd:attribute name="id" type="xsd:unsignedInt"/>
    <xsd:attribute name="definitionType" type="xsd:unsignedInt"/>
    <xsd:attribute name="type" type="xsd:string"/>
    <xsd:attribute name="dataType" type="xsd:string"/>
    <xsd:attribute name="formItem" type="xsd:string"/>
    <xsd:attribute name="unique" type="xsd:string"/>
    <xsd:attribute name="multipleAllowed" type="xsd:boolean"/>
    <xsd:attribute name="multipleAllowedInParent" type="xsd:boolean"/>
    <xsd:attribute name="canBeDeleted" type="xsd:boolean"/>
    <xsd:attribute name="x" type="xsd:unsignedInt"/>
    <xsd:attribute name="y" type="xsd:unsignedInt"/>
	<xsd:attribute name="feature" type="xsd:string"/>
    <xsd:attribute name="display" type="xsd:string"/>
    <xsd:attribute name="license" type="xsd:string"/>
    <xsd:attribute name="notLicense" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="propertiesType">
    <xsd:sequence>
      <xsd:element name="property" type="propertyType" minOccurs="1" maxOccurs="unbounded"/>
   </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="propertyType">
    <xsd:sequence>
      <xsd:element name="option" type="optionType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="option_entry_data" type="option_select_dataType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="workflowCondition" type="workflowConditionType" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="help" type="xsd:string" minOccurs="0" maxOccurs="1"/>
   </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="caption" type="xsd:string" use="required"/>
    <xsd:attribute name="type" type="xsd:string" use="required"/>
    <xsd:attribute name="commandName" type="xsd:string"/>
    <xsd:attribute name="default" type="xsd:string"/>
    <xsd:attribute name="value" type="xsd:string"/>
    <xsd:attribute name="setAttribute" type="xsd:string"/>
    <xsd:attribute name="inline" type="xsd:boolean"/>
    <xsd:attribute name="readonly" type="xsd:boolean"/>
    <xsd:attribute name="width" type="xsd:string"/>
    <xsd:attribute name="characterMask" type="xsd:string"/>
    <xsd:attribute name="characterLength" type="xsd:string"/>
    <xsd:attribute name="path" type="xsd:string"/>
    <xsd:attribute name="unique" type="xsd:string"/>
    <xsd:attribute name="multipleAllowed" type="xsd:boolean"/>
    <xsd:attribute name="definitionType" type="xsd:unsignedInt"/>
    <xsd:attribute name="status" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="optionsType">
    <xsd:sequence>
      <xsd:element name="option" type="optionType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="option_select" type="option_selectType" minOccurs="0" maxOccurs="unbounded"/>
 
    </xsd:sequence>
    <xsd:attribute name="optionCaption" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="optionType">
     <xsd:sequence>
		<xsd:element name="help" type="xsd:string" minOccurs="0" maxOccurs="1"/>
     </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string"/>
    <xsd:attribute name="caption" type="xsd:string"/>
    <xsd:attribute name="definitionType" type="xsd:string"/>
    <xsd:attribute name="initial" type="xsd:boolean"/>
    <xsd:attribute name="default" type="xsd:boolean"/>
    <xsd:attribute name="multipleAllowed" type="xsd:boolean"/>
  </xsd:complexType>

  <xsd:complexType name="option_selectType">
    <xsd:sequence>
      <xsd:element name="exclude" type="excludeType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="definitionType" type="xsd:string"/>
    <xsd:attribute name="path" type="xsd:string"/>
    <xsd:attribute name="optionCaption" type="xsd:string"/>
    <xsd:attribute name="initial" type="xsd:boolean"/>
    <xsd:attribute name="default" type="xsd:boolean"/>
  </xsd:complexType>


  <xsd:complexType name="option_select_dataType">
    <xsd:sequence>
      <xsd:element name="exclude" type="excludeType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="select_type" type="xsd:string"/>
    <xsd:attribute name="path" type="xsd:string"/>
    <xsd:attribute name="optionCaption" type="xsd:string"/>
    <xsd:attribute name="initial" type="xsd:boolean"/>
    <xsd:attribute name="default" type="xsd:boolean"/>
  </xsd:complexType>

  <xsd:complexType name="workflowConditionType">
     <xsd:sequence>
		<xsd:element name="value" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
     </xsd:sequence>
    <xsd:attribute name="definitionId" type="xsd:string"/>
    <xsd:attribute name="elementName" type="xsd:string"/>
    <xsd:attribute name="operation" type="xsd:string"/>
    <xsd:attribute name="duration" type="xsd:string"/>
    <xsd:attribute name="durationType" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="excludeType">
     <xsd:sequence/>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="jspsType">
    <xsd:sequence>
      <xsd:element name="jsp" type="jspType" minOccurs="0" maxOccurs="unbounded"/>
   </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="jspType">
     <xsd:sequence/>
    <xsd:attribute name="name" type="xsd:string"/>
    <xsd:attribute name="value" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="gwtFolderViewsType">
    <xsd:sequence>
      <xsd:element name="folderView" type="gwtFolderViewType" minOccurs="0" maxOccurs="unbounded"/>
   </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="gwtFolderViewType">
     <xsd:sequence/>
    <xsd:attribute name="name" type="xsd:string"/>
    <xsd:attribute name="value" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="indexType">
	<xsd:sequence>
	  <xsd:element name="args" type="optionalArgsType" minOccurs="0" maxOccurs="1"/>
	</xsd:sequence>
	<xsd:attribute name="apply" type="xsd:boolean" use="required" />
	<xsd:attribute name="fieldBuilder" type="xsd:string" use="required" />
  </xsd:complexType>
  

 <xsd:complexType name="notifyType">
	<xsd:sequence>
	  <xsd:element name="args" type="optionalArgsType" minOccurs="0" maxOccurs="1"/>
	</xsd:sequence>
	<xsd:attribute name="notifyBuilder" type="xsd:string"/>
	<xsd:attribute name="velocity" type="xsd:string"/>
  </xsd:complexType>
  
 <xsd:complexType name="webServiceType">
	<xsd:sequence>
	  <xsd:element name="args" type="optionalArgsType" minOccurs="0" maxOccurs="1"/>
	</xsd:sequence>
	<xsd:attribute name="apply" type="xsd:boolean" use="required" />
	<xsd:attribute name="elementBuilder" type="xsd:string" use="required" />
  </xsd:complexType>
  
   <xsd:complexType name="exportType">
	<xsd:sequence>
	  <xsd:element name="args" type="optionalArgsType" minOccurs="0" maxOccurs="1"/>
	</xsd:sequence>
	<xsd:attribute name="apply" type="xsd:boolean" use="required" />
	<xsd:attribute name="elementBuilder" type="xsd:string" use="required" />
  </xsd:complexType>
  
  <xsd:complexType name="optionalArgsType">
	<xsd:sequence>
		<xsd:element name="arg" type="optionalArgType" minOccurs="0" maxOccurs="unbounded" />
	</xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="optionalArgType">
	<xsd:attribute name="name" type="xsd:string" use="required" />	
	<xsd:attribute name="type" type="optionalArgDataType" use="required" />	
	<xsd:attribute name="value" type="xsd:string" use="required" />	
  </xsd:complexType>

  <xsd:simpleType name="optionalArgDataType">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="boolean"/>
		<xsd:enumeration value="string"/>
	</xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== new333333/test2/trunk/ssf/web/docroot/WEB-INF/classes/config/definition_builder_config.xml
<?xml version="1.0" encoding="UTF-8" ?>

<definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../resources/definition_builder_config.xsd">
	<definition name="entryTypeDefinition" definitionType="1" caption="__entry_definitions" canBeDeleted="false">		
		<operations>
			<operation name="addDefinition" item="entryType" caption="__add_a_new_entry_definition" />
		</operations>
	</definition>
	
	<definition name="workflowProcessDefinition" definitionType="2" caption="__workflow_processes" canBeDeleted="false">
		<operations>
			<operation name="addDefinition" item="workflowProcessType" caption="__add_a_new_workflow_process" />
		</operations>
	</definition>
	
	<definition name="forumViewDefinition" definitionType="5" caption="__forum_views" canBeDeleted="false">
		<operations>
			<operation name="addDefinition" item="forumViewType" caption="__add_a_new_forum_view" />
		</operations>
	</definition>
	
	<item name="entryType" definitionType="1" caption="__entry_definition">		
		<properties>
			<property name="name" caption="__name" type="text" />
			<property name="caption" caption="__caption" type="text" />
			<property name="replyStyle" caption="__reply_style" type="replyStyle" />
		</properties>
		
		<options>
			<option name="entryForm" initial="true" />
			<option name="entryView" initial="true" />
		</options>
	</item>
	
	<item name="workflowProcessType" definitionType="2" caption="__workflow_process">
		<properties>
			<property name="name" caption="__name" type="text" />
			<property name="caption" caption="__caption" type="text" />
		</properties>
		
		<options>
			<option name="workflowProcess" initial="true" />
		</options>
	</item>
	
	<item name="workflowProcess" caption="__workflow_process" canBeDeleted="false" multipleAllowed="false">
		<operations>
			<operation name="addOption" caption="__add" />
		</operations>

		<options>
			<option name="state" caption="__state" multipleAllowed="true" />
		</options>
	</item>
	
	<item name="forumViewType" definitionType="5" caption="__forum_view_definition">		
		<properties>
			<property name="name" caption="__name" type="text" />
			<property name="caption" caption="__caption" type="text" />
		</properties>
		
		<options>
			<option name="forumView" caption="__forum_view" initial="true" multipleAllowed="false" />
		</options>
	</item>
	
	<item name="forumView" definitionType="5" caption="__forum_view" canBeDeleted="false" multipleAllowed="false" >		
		<properties>
			<property name="type" caption="__type" type="selectbox" default="folder">
				<option name="folder" caption="__folder_folder" />
				<option name="file" caption="__folder_file" />
				<option name="event" caption="__folder_event" />
				<help>__help_forum_view_type</help>
			</property>
		</properties>
		<options>
			<option_select path="//item[@category='forumView']" />
			<option_select path="//item[@category='generalLayout']" optionCaption="__layout_options" />
		</options>
	</item>
	
	<item name="entryForm" caption="__entry_form_definition" canBeDeleted="false" multipleAllowed="false">
		<operations>
			<operation name="addOption" caption="__add" />
		</operations>

		<options>
			<option name="entryFormForm" initial="true" />
			<option_select path="//item[@category='generalLayout']" optionCaption="__layout_options" />
		</options>
		
		<jsps>
			<jsp name="form" value="/WEB-INF/jsp/definition_elements/entry_form.jsp" />
		</jsps>
	</item>

	<item name="entryView" caption="__entry_view_definition" canBeDeleted="false" multipleAllowed="false">
		<operations>
			<operation name="addOption" caption="__add" />
		</operations>

		<options>
			<option name="entryDataItem" caption="__entry_data_item" />
			<option name="entryAttachments" caption="__entry_attachments" />
			<option name="entryReplies" caption="__entry_replies" />
			<option_select path="//item[@category='entryLayout']" optionCaption="__entry_layout_options" />
			<option_select path="//item[@category='generalLayout']" optionCaption="__general_layout_options" />
		</options>
		
		<jsps>
			<jsp name="view" value="/WEB-INF/jsp/definition_elements/entry_view.jsp" />
		</jsps>
	</item>
	
	<item name="entryDataItem" type="dataView" caption="__entry_data_item" category="entryViewData">
		<properties>
			<property name="name" caption="__data_item_name" type="selectbox">
			    <option_entry_data select_type="data" optionCaption="__data_items_from_the_entry_form" />
			</property>
			<property name="caption" caption="__caption" type="text"/>
		</properties>
		<jsps>
			<jsp name="view" value="/WEB-INF/jsp/definition_elements/view_entry_data.jsp" />
		</jsps>
	</item>
		
	<item name="entryAttachments" type="dataView" caption="__entry_attachments" category="entryViewData">
		<properties>
			<property name="caption" caption="__caption" type="text"/>
		</properties>
		<jsps>
			<jsp name="view" value="/WEB-INF/jsp/definition_elements/view_entry_attachments.jsp" />
		</jsps>
	</item>
		
	<item name="entryReplies" type="dataView" caption="__entry_replies" category="entryViewData">
		<properties>
			<property name="caption" caption="__caption" type="text"/>
		</properties>
		<jsps>
			<jsp name="view" value="/WEB-INF/jsp/definition_elements/view_entry_replies.jsp" />
		</jsps>
	</item>
		
	<item name="entryFormForm" caption="__form" canBeDeleted="false" multipleAllowed="false">
		<properties>
			<property name="name" caption="__form_name" type="text" characterMask="^[a-zA-Z][a-zA-Z0-9_-]*$" setAttribute="formName"/>
		</properties>
		<options>
			<option name="title" initial="true" />
			<option name="entryFormButtons" initial="true" />
			<option_select path="//item[@category='entryData']" />
			<option_select path="//item[@category='entryLayout']" />
			<option_select path="//item[@category='generalLayout']" optionCaption="__layout_options" />
		</options>
		<jsps>
			<jsp name="form" value="/WEB-INF/jsp/definition_elements/form_form.jsp" />
		</jsps>
	</item>
		
	<item name="title" caption="__title" type="data" canBeDeleted="false" multipleAllowed="false" category="entryData">
		<properties>
			<property name="name" caption="__data_name" type="text" value="title" readonly="true">
				<help>__help_data_name</help>
			</property>
			<property name="caption" caption="__caption" type="text" value="__title"/>
			<property name="width" caption="__width" type="text"/>
			<property name="inline" caption="__inline" type="boolean">
				<help>__help_mark_as_inline</help>
			</property>
		</properties>
		<jsps>
			<jsp name="form" value="/WEB-INF/jsp/definition_elements/title_form.jsp" />
			<jsp name="view" value="/WEB-INF/jsp/definition_elements/title_view.jsp" />
		</jsps>
		<help>__help_title_field</help>
		<index apply="true" fieldBuilder="com.sitescape.ef.module.definition.index.FieldBuilderTitle" />
	</item>
	
	<item name="text" caption="__text" type="data" category="entryData">
		<properties>
			<property name="name" caption="__data_name" type="text" characterMask="^[a-zA-Z][a-zA-Z0-9_-]*$">
				<help>__help_data_name</help>
			</property>
			<property name="caption" caption="__caption" type="text"/>
			<property name="width" caption="__width" type="text"/>
			<property name="inline" caption="__inline" type="boolean">
				<help>__help_mark_as_inline</help>
			</property>
			<property name="required" caption="__required" type="boolean" default="false">
				<help>__help_required</help>
			</property>
		</properties>
		<jsps>
			<jsp name="form" value="/WEB-INF/jsp/definition_elements/text_form.jsp" />
		</jsps>
		<index apply="true" fieldBuilder="com.sitescape.ef.module.definition.index.FieldBuilderText" />
	</item>
	
	<item name="textarea" caption="__simple_text_area" type="data" category="entryData">
		<properties>
			<property name="name" caption="__data_name" type="text" characterMask="^[a-zA-Z][a-zA-Z0-9_-]*$">
				<help>__help_data_name</help>
			</property>
			<property name="caption" caption="__caption" type="text"/>
			<property name="width" caption="__width" type="text"/>
			<property name="rows" caption="__rows" type="text"/>
			<property name="inline" caption="__inline" type="boolean">
				<help>__help_mark_as_inline</help>
			</property>
			<property name="required" caption="__required" type="boolean" default="false">
				<help>__help_required</help>
			</property>
		</properties>
		<jsps>
			<jsp name="form" value="/WEB-INF/jsp/definition_elements/textarea_form.jsp" />
		</jsps>
		<index apply="true" fieldBuilder="com.sitescape.ef.module.definition.index.FieldBuilderText" />
	</item>
	
	<item name="htmlEditorTextarea" caption="__html_editor_text_area" type="data" category="entryData">
		<properties>
			<property name="name" caption="__data_name" type="text" characterMask="^[a-zA-Z][a-zA-Z0-9_-]*$">
				<help>__help_data_name</help>
			</property>
			<property name="caption" caption="__caption" type="text"/>
			<property name="height" caption="__height_px" type="text"/>
			<property name="required" caption="__required" type="boolean" default="false">
				<help>__help_required</help>
			</property>
		</properties>
		<jsps>
			<jsp name="form" value="/WEB-INF/jsp/definition_elements/html_editor_textarea_form.jsp" />
		</jsps>
		<index apply="true" fieldBuilder="com.sitescape.ef.module.definition.index.FieldBuilderDescription" />
	</item>
	
	<item name="event" caption="__event" type="data" category="entryData">
		<properties>
			<property name="name" caption="__data_name" type="text" characterMask="^[a-zA-Z][a-zA-Z0-9_-]*$">
				<help>__help_data_name</help>
			</property>
			<property name="caption" caption="__caption" type="text"/>
			<property name="hasDuration" caption="__has_a_duration" type="boolean" default="true"/>
